# Generated by Django 6.0.6 on 2026-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Tenant', 'Tenant'), ('Broker', 'Broker'), ('Owner', 'Owner')], max_length=20)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
